require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PurgesController do

  # This should return the minimal set of attributes required to create a valid
  # Purge. As you add validations to Purge, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "hostname" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PurgesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all purges as @purges" do
      purge = Purge.create! valid_attributes
      get :index, {}, valid_session
      assigns(:purges).should eq([purge])
    end
  end

  describe "GET show" do
    it "assigns the requested purge as @purge" do
      purge = Purge.create! valid_attributes
      get :show, {:id => purge.to_param}, valid_session
      assigns(:purge).should eq(purge)
    end
  end

  describe "GET new" do
    it "assigns a new purge as @purge" do
      get :new, {}, valid_session
      assigns(:purge).should be_a_new(Purge)
    end
  end

  describe "GET edit" do
    it "assigns the requested purge as @purge" do
      purge = Purge.create! valid_attributes
      get :edit, {:id => purge.to_param}, valid_session
      assigns(:purge).should eq(purge)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Purge" do
        expect {
          post :create, {:purge => valid_attributes}, valid_session
        }.to change(Purge, :count).by(1)
      end

      it "assigns a newly created purge as @purge" do
        post :create, {:purge => valid_attributes}, valid_session
        assigns(:purge).should be_a(Purge)
        assigns(:purge).should be_persisted
      end

      it "redirects to the created purge" do
        post :create, {:purge => valid_attributes}, valid_session
        response.should redirect_to(Purge.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved purge as @purge" do
        # Trigger the behavior that occurs when invalid params are submitted
        Purge.any_instance.stub(:save).and_return(false)
        post :create, {:purge => { "hostname" => "invalid value" }}, valid_session
        assigns(:purge).should be_a_new(Purge)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Purge.any_instance.stub(:save).and_return(false)
        post :create, {:purge => { "hostname" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested purge" do
        purge = Purge.create! valid_attributes
        # Assuming there are no other purges in the database, this
        # specifies that the Purge created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Purge.any_instance.should_receive(:update_attributes).with({ "hostname" => "MyString" })
        put :update, {:id => purge.to_param, :purge => { "hostname" => "MyString" }}, valid_session
      end

      it "assigns the requested purge as @purge" do
        purge = Purge.create! valid_attributes
        put :update, {:id => purge.to_param, :purge => valid_attributes}, valid_session
        assigns(:purge).should eq(purge)
      end

      it "redirects to the purge" do
        purge = Purge.create! valid_attributes
        put :update, {:id => purge.to_param, :purge => valid_attributes}, valid_session
        response.should redirect_to(purge)
      end
    end

    describe "with invalid params" do
      it "assigns the purge as @purge" do
        purge = Purge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Purge.any_instance.stub(:save).and_return(false)
        put :update, {:id => purge.to_param, :purge => { "hostname" => "invalid value" }}, valid_session
        assigns(:purge).should eq(purge)
      end

      it "re-renders the 'edit' template" do
        purge = Purge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Purge.any_instance.stub(:save).and_return(false)
        put :update, {:id => purge.to_param, :purge => { "hostname" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested purge" do
      purge = Purge.create! valid_attributes
      expect {
        delete :destroy, {:id => purge.to_param}, valid_session
      }.to change(Purge, :count).by(-1)
    end

    it "redirects to the purges list" do
      purge = Purge.create! valid_attributes
      delete :destroy, {:id => purge.to_param}, valid_session
      response.should redirect_to(purges_url)
    end
  end

end
